
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 06 20:04:15 CET 2016
//----------------------------------------------------

package compilador;

import java_cup.runtime.*;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.File;
import java.util.Scanner;
import compilador.TablaSimbolos;
import java.util.Queue;
import java.util.LinkedList;
import java.util.NoSuchElementException;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Tue Dec 06 20:04:15 CET 2016
  */
public class ParserCup extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ParserCup() {super();}

  /** Constructor which sets the default scanner. */
  public ParserCup(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserCup(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\064\000\002\002\004\000\002\002\007\000\002\002" +
    "\006\000\002\003\005\000\002\004\003\000\002\004\004" +
    "\000\002\005\007\000\002\005\007\000\002\005\004\000" +
    "\002\006\005\000\002\006\003\000\002\007\004\000\002" +
    "\007\003\000\002\011\006\000\002\011\006\000\002\011" +
    "\005\000\002\011\005\000\002\011\005\000\002\011\003" +
    "\000\002\011\011\000\002\011\013\000\002\011\011\000" +
    "\002\011\013\000\002\011\011\000\002\011\011\000\002" +
    "\011\004\000\002\010\003\000\002\010\003\000\002\010" +
    "\005\000\002\010\005\000\002\010\005\000\002\010\005" +
    "\000\002\010\005\000\002\010\005\000\002\010\005\000" +
    "\002\010\004\000\002\010\004\000\002\010\005\000\002" +
    "\010\005\000\002\010\005\000\002\010\005\000\002\010" +
    "\005\000\002\010\005\000\002\010\005\000\002\010\005" +
    "\000\002\012\003\000\002\012\003\000\002\012\005\000" +
    "\002\012\005\000\002\012\005\000\002\012\005\000\002" +
    "\012\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\201\000\004\004\006\001\002\000\004\002\203\001" +
    "\002\000\010\003\012\006\013\010\011\001\002\000\004" +
    "\051\007\001\002\000\004\005\010\001\002\000\010\003" +
    "\ufffe\006\ufffe\010\ufffe\001\002\000\004\051\172\001\002" +
    "\000\004\043\171\001\002\000\020\003\026\013\020\014" +
    "\025\015\027\016\021\020\023\051\030\001\002\000\004" +
    "\006\017\001\002\000\010\003\012\006\ufffd\010\011\001" +
    "\002\000\004\006\ufffc\001\002\000\020\003\026\013\020" +
    "\014\025\015\027\016\021\020\023\051\030\001\002\000" +
    "\010\044\067\050\040\051\034\001\002\000\016\025\032" +
    "\026\033\027\036\044\035\050\040\051\034\001\002\000" +
    "\024\003\026\007\ufff5\013\020\014\025\015\027\016\021" +
    "\020\023\022\ufff5\051\030\001\002\000\016\025\032\026" +
    "\033\027\036\044\035\050\040\051\034\001\002\000\004" +
    "\007\121\001\002\000\016\025\032\026\033\027\036\044" +
    "\035\050\040\051\034\001\002\000\004\043\114\001\002" +
    "\000\024\003\uffef\007\uffef\013\uffef\014\uffef\015\uffef\016" +
    "\uffef\020\uffef\022\uffef\051\uffef\001\002\000\004\030\031" +
    "\001\002\000\016\025\032\026\033\027\036\044\035\050" +
    "\040\051\034\001\002\000\016\025\032\026\033\027\036" +
    "\044\035\050\040\051\034\001\002\000\016\017\uffe7\021" +
    "\uffe7\023\uffe7\024\uffe7\043\uffe7\045\uffe7\001\002\000\042" +
    "\017\uffd4\021\uffd4\023\uffd4\024\uffd4\031\uffd4\032\uffd4\033" +
    "\uffd4\034\uffd4\035\uffd4\036\uffd4\037\uffd4\040\uffd4\041\uffd4" +
    "\042\uffd4\043\uffd4\045\uffd4\001\002\000\016\025\032\026" +
    "\033\027\036\044\035\050\040\051\034\001\002\000\016" +
    "\017\uffe6\021\uffe6\023\uffe6\024\uffe6\043\uffe6\045\uffe6\001" +
    "\002\000\010\023\061\024\062\043\106\001\002\000\042" +
    "\017\uffd3\021\uffd3\023\uffd3\024\uffd3\031\uffd3\032\uffd3\033" +
    "\uffd3\034\uffd3\035\uffd3\036\uffd3\037\uffd3\040\uffd3\041\uffd3" +
    "\042\uffd3\043\uffd3\045\uffd3\001\002\000\034\023\043\024" +
    "\056\031\042\032\044\033\052\034\051\035\050\036\046" +
    "\037\045\040\055\041\047\042\054\043\053\001\002\000" +
    "\010\044\067\050\040\051\034\001\002\000\016\025\032" +
    "\026\033\027\036\044\035\050\040\051\034\001\002\000" +
    "\010\044\067\050\040\051\034\001\002\000\010\044\067" +
    "\050\040\051\034\001\002\000\010\044\067\050\040\051" +
    "\034\001\002\000\010\044\067\050\040\051\034\001\002" +
    "\000\010\044\067\050\040\051\034\001\002\000\010\044" +
    "\067\050\040\051\034\001\002\000\010\044\067\050\040" +
    "\051\034\001\002\000\024\003\ufff4\007\ufff4\013\ufff4\014" +
    "\ufff4\015\ufff4\016\ufff4\020\ufff4\022\ufff4\051\ufff4\001\002" +
    "\000\010\044\067\050\040\051\034\001\002\000\010\044" +
    "\067\050\040\051\034\001\002\000\016\025\032\026\033" +
    "\027\036\044\035\050\040\051\034\001\002\000\016\017" +
    "\uffda\021\uffda\023\uffda\024\uffda\043\uffda\045\uffda\001\002" +
    "\000\042\017\uffdb\021\uffdb\023\uffdb\024\uffdb\031\042\032" +
    "\044\033\052\034\051\035\050\036\046\037\045\040\055" +
    "\041\047\042\054\043\uffdb\045\uffdb\001\002\000\016\025" +
    "\032\026\033\027\036\044\035\050\040\051\034\001\002" +
    "\000\016\025\032\026\033\027\036\044\035\050\040\051" +
    "\034\001\002\000\016\017\uffdc\021\uffdc\023\uffdc\024\uffdc" +
    "\043\uffdc\045\uffdc\001\002\000\042\017\uffd9\021\uffd9\023" +
    "\uffd9\024\uffd9\031\042\032\044\033\052\034\051\035\050" +
    "\036\046\037\045\040\055\041\047\042\054\043\uffd9\045" +
    "\uffd9\001\002\000\016\017\uffd8\021\uffd8\023\uffd8\024\uffd8" +
    "\043\uffd8\045\uffd8\001\002\000\042\017\uffd5\021\uffd5\023" +
    "\uffd5\024\uffd5\031\042\032\044\033\052\034\051\035\050" +
    "\036\046\037\045\040\055\041\047\042\054\043\uffd5\045" +
    "\uffd5\001\002\000\010\044\067\050\040\051\034\001\002" +
    "\000\042\017\uffd0\021\uffd0\023\uffd0\024\uffd0\031\uffd0\032" +
    "\uffd0\033\uffd0\034\uffd0\035\uffd0\036\uffd0\037\uffd0\040\uffd0" +
    "\041\047\042\054\043\uffd0\045\uffd0\001\002\000\014\037" +
    "\045\040\055\041\047\042\054\045\072\001\002\000\042" +
    "\017\uffd2\021\uffd2\023\uffd2\024\uffd2\031\uffd2\032\uffd2\033" +
    "\uffd2\034\uffd2\035\uffd2\036\uffd2\037\uffd2\040\uffd2\041\uffd2" +
    "\042\uffd2\043\uffd2\045\uffd2\001\002\000\042\017\uffce\021" +
    "\uffce\023\uffce\024\uffce\031\uffce\032\uffce\033\uffce\034\uffce" +
    "\035\uffce\036\uffce\037\uffce\040\uffce\041\uffce\042\uffce\043" +
    "\uffce\045\uffce\001\002\000\026\017\uffe2\021\uffe2\023\uffe2" +
    "\024\uffe2\037\045\040\055\041\047\042\054\043\uffe2\045" +
    "\uffe2\001\002\000\026\017\uffdf\021\uffdf\023\uffdf\024\uffdf" +
    "\037\045\040\055\041\047\042\054\043\uffdf\045\uffdf\001" +
    "\002\000\026\017\uffe1\021\uffe1\023\uffe1\024\uffe1\037\045" +
    "\040\055\041\047\042\054\043\uffe1\045\uffe1\001\002\000" +
    "\042\017\uffcf\021\uffcf\023\uffcf\024\uffcf\031\uffcf\032\uffcf" +
    "\033\uffcf\034\uffcf\035\uffcf\036\uffcf\037\uffcf\040\uffcf\041" +
    "\uffcf\042\uffcf\043\uffcf\045\uffcf\001\002\000\026\017\uffe4" +
    "\021\uffe4\023\uffe4\024\uffe4\037\045\040\055\041\047\042" +
    "\054\043\uffe4\045\uffe4\001\002\000\042\017\uffd1\021\uffd1" +
    "\023\uffd1\024\uffd1\031\uffd1\032\uffd1\033\uffd1\034\uffd1\035" +
    "\uffd1\036\uffd1\037\uffd1\040\uffd1\041\047\042\054\043\uffd1" +
    "\045\uffd1\001\002\000\026\017\uffe0\021\uffe0\023\uffe0\024" +
    "\uffe0\037\045\040\055\041\047\042\054\043\uffe0\045\uffe0" +
    "\001\002\000\016\017\uffd6\021\uffd6\023\uffd6\024\uffd6\043" +
    "\uffd6\045\uffd6\001\002\000\042\017\uffd7\021\uffd7\023\uffd7" +
    "\024\uffd7\031\042\032\044\033\052\034\051\035\050\036" +
    "\046\037\045\040\055\041\047\042\054\043\uffd7\045\uffd7" +
    "\001\002\000\026\017\uffe3\021\uffe3\023\uffe3\024\uffe3\037" +
    "\045\040\055\041\047\042\054\043\uffe3\045\uffe3\001\002" +
    "\000\024\003\ufff3\007\ufff3\013\ufff3\014\ufff3\015\ufff3\016" +
    "\ufff3\020\ufff3\022\ufff3\051\ufff3\001\002\000\010\023\061" +
    "\024\062\045\111\001\002\000\034\023\043\024\056\031" +
    "\042\032\044\033\052\034\051\035\050\036\046\037\045" +
    "\040\055\041\047\042\054\045\072\001\002\000\016\017" +
    "\uffe5\021\uffe5\023\uffe5\024\uffe5\043\uffe5\045\uffe5\001\002" +
    "\000\016\017\uffde\021\uffde\023\uffde\024\uffde\043\uffde\045" +
    "\uffde\001\002\000\042\017\uffdd\021\uffdd\023\uffdd\024\uffdd" +
    "\031\042\032\044\033\052\034\051\035\050\036\046\037" +
    "\045\040\055\041\047\042\054\043\uffdd\045\uffdd\001\002" +
    "\000\024\003\uffe8\007\uffe8\013\uffe8\014\uffe8\015\uffe8\016" +
    "\uffe8\020\uffe8\022\uffe8\051\uffe8\001\002\000\010\023\061" +
    "\024\062\043\120\001\002\000\034\023\043\024\056\031" +
    "\042\032\044\033\052\034\051\035\050\036\046\037\045" +
    "\040\055\041\047\042\054\043\117\001\002\000\024\003" +
    "\ufff1\007\ufff1\013\ufff1\014\ufff1\015\ufff1\016\ufff1\020\ufff1" +
    "\022\ufff1\051\ufff1\001\002\000\024\003\ufff0\007\ufff0\013" +
    "\ufff0\014\ufff0\015\ufff0\016\ufff0\020\ufff0\022\ufff0\051\ufff0" +
    "\001\002\000\004\002\000\001\002\000\010\021\136\023" +
    "\061\024\062\001\002\000\034\021\124\023\043\024\056" +
    "\031\042\032\044\033\052\034\051\035\050\036\046\037" +
    "\045\040\055\041\047\042\054\001\002\000\020\003\026" +
    "\013\020\014\025\015\027\016\021\020\023\051\030\001" +
    "\002\000\006\007\127\022\126\001\002\000\020\003\026" +
    "\013\020\014\025\015\027\016\021\020\023\051\030\001" +
    "\002\000\004\020\130\001\002\000\004\043\131\001\002" +
    "\000\024\003\uffec\007\uffec\013\uffec\014\uffec\015\uffec\016" +
    "\uffec\020\uffec\022\uffec\051\uffec\001\002\000\004\007\133" +
    "\001\002\000\004\020\134\001\002\000\004\043\135\001" +
    "\002\000\024\003\uffeb\007\uffeb\013\uffeb\014\uffeb\015\uffeb" +
    "\016\uffeb\020\uffeb\022\uffeb\051\uffeb\001\002\000\020\003" +
    "\026\013\020\014\025\015\027\016\021\020\023\051\030" +
    "\001\002\000\006\007\141\022\140\001\002\000\020\003" +
    "\026\013\020\014\025\015\027\016\021\020\023\051\030" +
    "\001\002\000\004\020\142\001\002\000\004\043\143\001" +
    "\002\000\024\003\uffee\007\uffee\013\uffee\014\uffee\015\uffee" +
    "\016\uffee\020\uffee\022\uffee\051\uffee\001\002\000\004\007" +
    "\145\001\002\000\004\020\146\001\002\000\004\043\147" +
    "\001\002\000\024\003\uffed\007\uffed\013\uffed\014\uffed\015" +
    "\uffed\016\uffed\020\uffed\022\uffed\051\uffed\001\002\000\006" +
    "\007\ufff6\022\ufff6\001\002\000\010\017\160\023\061\024" +
    "\062\001\002\000\034\017\153\023\043\024\056\031\042" +
    "\032\044\033\052\034\051\035\050\036\046\037\045\040" +
    "\055\041\047\042\054\001\002\000\020\003\026\013\020" +
    "\014\025\015\027\016\021\020\023\051\030\001\002\000" +
    "\004\007\155\001\002\000\004\016\156\001\002\000\004" +
    "\043\157\001\002\000\024\003\uffe9\007\uffe9\013\uffe9\014" +
    "\uffe9\015\uffe9\016\uffe9\020\uffe9\022\uffe9\051\uffe9\001\002" +
    "\000\020\003\026\013\020\014\025\015\027\016\021\020" +
    "\023\051\030\001\002\000\004\007\162\001\002\000\004" +
    "\016\163\001\002\000\004\043\164\001\002\000\024\003" +
    "\uffea\007\uffea\013\uffea\014\uffea\015\uffea\016\uffea\020\uffea" +
    "\022\uffea\051\uffea\001\002\000\014\037\045\040\055\041" +
    "\047\042\054\043\166\001\002\000\024\003\ufff2\007\ufff2" +
    "\013\ufff2\014\ufff2\015\ufff2\016\ufff2\020\ufff2\022\ufff2\051" +
    "\ufff2\001\002\000\004\007\170\001\002\000\004\002\uffff" +
    "\001\002\000\010\003\ufff9\006\ufff9\010\ufff9\001\002\000" +
    "\006\046\ufff7\047\ufff7\001\002\000\006\046\174\047\175" +
    "\001\002\000\004\051\202\001\002\000\006\011\176\012" +
    "\177\001\002\000\004\043\201\001\002\000\004\043\200" +
    "\001\002\000\010\003\ufffa\006\ufffa\010\ufffa\001\002\000" +
    "\010\003\ufffb\006\ufffb\010\ufffb\001\002\000\006\046\ufff8" +
    "\047\ufff8\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\201\000\006\002\003\003\004\001\001\000\002\001" +
    "\001\000\006\004\013\005\014\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\006\172\001" +
    "\001\000\002\001\001\000\006\007\166\011\021\001\001" +
    "\000\002\001\001\000\006\004\015\005\014\001\001\000" +
    "\002\001\001\000\006\007\023\011\021\001\001\000\004" +
    "\012\164\001\001\000\006\010\150\012\151\001\001\000" +
    "\006\007\147\011\021\001\001\000\006\010\121\012\122" +
    "\001\001\000\002\001\001\000\006\010\114\012\115\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\010\036\012\040\001\001\000\006\010\111\012" +
    "\112\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\010\106\012\107\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\012\104" +
    "\001\001\000\006\010\102\012\103\001\001\000\004\012" +
    "\101\001\001\000\004\012\100\001\001\000\004\012\077" +
    "\001\001\000\004\012\076\001\001\000\004\012\075\001" +
    "\001\000\004\012\074\001\001\000\004\012\073\001\001" +
    "\000\002\001\001\000\004\012\072\001\001\000\004\012" +
    "\067\001\001\000\006\010\056\012\057\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\010\064\012\065\001" +
    "\001\000\006\010\062\012\063\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\012\070\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\007\124\011\021\001\001\000\002\001\001\000" +
    "\006\007\131\011\021\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\007\136" +
    "\011\021\001\001\000\002\001\001\000\006\007\143\011" +
    "\021\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\007\153\011\021\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\007\160\011\021\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserCup$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserCup$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserCup$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




static public TablaSimbolos tablaSimbolos;
static public Queue<String> colaDeclarados; //Utilizado para procesar declaraciones multiples en una linea
static public Ast arbol; //Para almacenar el AST

/** MAIN - LEER TOKENS */

public static void main (String argv[]) throws Exception
  {
    /*Comprobacacion del nombre del archivo*/
    if(argv.length<1){
    	System.err.println("Uso: java Parser nombreArchivo");
    	System.exit(1);
    }
    /* Asegurarse que la extension del archivo es correcta*/
	int aux = argv[0].indexOf('.');
	if(aux==-1){
		System.err.println("Error: El archivo debe acabar en .prog");
		System.exit(1);
	} else{
		if(!argv[0].substring(aux+1).equals("prog")){
			System.err.println("Error: El archivo debe acabar en .prog");
			System.exit(1);
		}
	}
	/* Inicializaion*/
	File archivo = new File(argv[0]);
    FileReader fr = new FileReader(archivo);
    tablaSimbolos = new TablaSimbolos();
    colaDeclarados = new LinkedList();
    arbol = new Ast();
    Scan lex = new Scan(fr);
    ParserCup p = new ParserCup(lex);
    p.parse();
}

/** NOTIFICAR ERROR DE SINTAXIS */
public void syntax_error(Symbol s) {
  report_error("Error de sintaxis linea " + s.left, null);
}

/** NOTIFICAR ERROR FATAL Y SALIR */
public void report_fatal_error(String message, Object info) {
  done_parsing();
  report_error("Error de sintaxis fatal : "
  + "No se puede recuperar del error y continuar con el analisis - "
  + message + " ",(Symbol)info);
  report_error("** Final del analisis.", null);
  System.exit(1);
}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ParserCup$actions {
  private final ParserCup parser;

  /** Constructor */
  CUP$ParserCup$actions(ParserCup parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$ParserCup$do_action(
    int                        CUP$ParserCup$act_num,
    java_cup.runtime.lr_parser CUP$ParserCup$parser,
    java.util.Stack            CUP$ParserCup$stack,
    int                        CUP$ParserCup$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserCup$result;

      /* select the action based on the action number */
      switch (CUP$ParserCup$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expresion ::= expresion DIVISION expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
					Nodo aux1 = (Nodo)e1;
					Nodo aux2 = (Nodo)e2;
					if((aux1.getTipo().equals("Integer")||aux1.getTipo().equals("OP"))&&(aux2.getTipo().equals("Integer")||aux2.getTipo().equals("OP"))){
						RESULT = new Nodo((String)v, "OP", (Nodo)e1, (Nodo)e2);;
						System.out.println("Expresion división");
					} else System.err.println("Error semántico: Expresión de tipo inesperado en operación de enteros" + " (Linea " + vleft + ")");
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expresion",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expresion ::= expresion MULTIPLICACION expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
					Nodo aux1 = (Nodo)e1;
					Nodo aux2 = (Nodo)e2;
					if((aux1.getTipo().equals("Integer")||aux1.getTipo().equals("OP"))&&(aux2.getTipo().equals("Integer")||aux2.getTipo().equals("OP"))){
						RESULT = new Nodo((String)v, "OP", (Nodo)e1, (Nodo)e2);
						System.out.println("Expresion multiplicacion");
					} else System.err.println("Error semántico: Expresión de tipo inesperado en operación de enteros" + " (Linea " + vleft + ")");
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expresion",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expresion ::= expresion RESTA expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
					Nodo aux1 = (Nodo)e1;
					Nodo aux2 = (Nodo)e2;
					if((aux1.getTipo().equals("Integer")||aux1.getTipo().equals("OP"))&&(aux2.getTipo().equals("Integer")||aux2.getTipo().equals("OP"))){
						RESULT = new Nodo((String)v, "OP", (Nodo)e1, (Nodo)e2);
						System.out.println("Expresion resto");
					} else System.err.println("Error semántico: Expresión de tipo inesperado en operación de enteros" + " (Linea " + vleft + ")");
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expresion",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expresion ::= expresion SUMA expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
					Nodo aux1 = (Nodo)e1;
					Nodo aux2 = (Nodo)e2;
					if((aux1.getTipo().equals("Integer")||aux1.getTipo().equals("OP"))&&(aux2.getTipo().equals("Integer")||aux2.getTipo().equals("OP"))){
						RESULT = new Nodo((String)v, "OP", (Nodo)e1, (Nodo)e2);//Creamos nodo con hijos como operadores
						System.out.println("Expresion suma");
					} else System.err.println("Error semántico: Expresión de tipo inesperado en operación de enteros" + " (Linea " + vleft + ")");
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expresion",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expresion ::= ABRIRPARENTESIS expresion CERRARPARENTESIS 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
					RESULT = new Nodo ("Parentesis", "OP", (Nodo)e1, null);
					System.out.println("expresion anidada");
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expresion",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expresion ::= ENTERO 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
					RESULT = new Nodo((String)v, "Integer", null, null);
					System.out.println("Expresion Entero");
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expresion",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expresion ::= IDENTIFICADOR 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
					String aux = ParserCup.tablaSimbolos.getSimbolo((String)v);
					if (aux.equals("Undefined")){
						//No existe en la tabla. Error
						System.err.println("Error semántico: Llamada a variable no declarada" + " (Linea " + vleft + ", Pos " + vright +")");
					} else {
						System.out.println("Expresion Identificador tipo " + aux);
						RESULT = new Nodo((String)v, aux, null, null);//creamos nodo con identificador y lo subimos
					}
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expresion",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // condicion ::= condicion AND expresion 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
				Nodo aux1 = (Nodo) c;
				Nodo aux2 = (Nodo) e;
				if((aux1.getTipo().equals("Boolean")||aux1.getTipo().equals("Cond"))&&(aux2.getTipo().equals("Boolean")||aux2.getTipo().equals("Cond"))){
					RESULT = new Nodo ((String)v, "Cond", (Nodo)c, (Nodo)e);
					System.out.println("Condicion and simple");
				} else System.err.println("Error semántico: Expresión de tipo inesperado en operación booleana" + " (Linea " + cleft + ")");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // condicion ::= expresion AND condicion 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
				Nodo aux1 = (Nodo) e;
				Nodo aux2 = (Nodo) c;
				if((aux1.getTipo().equals("Boolean")||aux1.getTipo().equals("Cond"))&&(aux2.getTipo().equals("Boolean")||aux2.getTipo().equals("Cond"))){
					RESULT = new Nodo ((String)v, "Cond", (Nodo)e, (Nodo)c);
					System.out.println("Condicion and mixta");
				} else System.err.println("Error semántico: Expresión de tipo inesperado en operación booleana" + " (Linea " + cleft + ")");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // condicion ::= expresion AND expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
				Nodo aux1 = (Nodo) e1;
				Nodo aux2 = (Nodo) e2;
				if((aux1.getTipo().equals("Boolean")||aux1.getTipo().equals("Cond"))&&(aux2.getTipo().equals("Boolean")||aux2.getTipo().equals("Cond"))){
					RESULT = new Nodo ((String)v, "Cond", (Nodo)e1, (Nodo)e2);
					System.out.println("Condicion and ambigua");
				} else System.err.println("Error semántico: Expresión de tipo inesperado en operación booleana" + " (Linea " + e1left + ")");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // condicion ::= condicion AND condicion 
            {
              Object RESULT =null;
		int c1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int c1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object c1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int c2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int c2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object c2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
				Nodo aux1 = (Nodo) c1;
				Nodo aux2 = (Nodo) c2;
				if((aux1.getTipo().equals("Boolean")||aux1.getTipo().equals("Cond"))&&(aux2.getTipo().equals("Boolean")||aux2.getTipo().equals("Cond"))){
					RESULT = new Nodo ((String)v, "Cond", (Nodo)c1, (Nodo)c2);
					System.out.println("Condicion and simple");
				} else System.err.println("Error semántico: Expresión de tipo inesperado en operación booleana" + " (Linea " + c1left + ")");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // condicion ::= condicion OR expresion 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
				Nodo aux1 = (Nodo) c;
				Nodo aux2 = (Nodo) e;
				if((aux1.getTipo().equals("Boolean")||aux1.getTipo().equals("Cond"))&&(aux2.getTipo().equals("Boolean")||aux2.getTipo().equals("Cond"))){
					RESULT = new Nodo ((String)v, "Cond", (Nodo)c, (Nodo)e);
					System.out.println("Condicion or mixta");
				} else System.err.println("Error semántico: Expresión de tipo inesperado en operación booleana" + " (Linea " + cleft + ")");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // condicion ::= expresion OR condicion 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
				Nodo aux1 = (Nodo) e;
				Nodo aux2 = (Nodo) c;
				if((aux1.getTipo().equals("Boolean")||aux1.getTipo().equals("Cond"))&&(aux2.getTipo().equals("Boolean")||aux2.getTipo().equals("Cond"))){
					RESULT = new Nodo ((String)v, "Cond", (Nodo)e, (Nodo)c);
					System.out.println("Condicion or mixta");
				} else System.err.println("Error semántico: Expresión de tipo inesperado en operación booleana" + " (Linea " + eleft + ")");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // condicion ::= expresion OR expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
				Nodo aux1 = (Nodo) e1;
				Nodo aux2 = (Nodo) e2;
				if((aux1.getTipo().equals("Boolean")||aux1.getTipo().equals("Cond"))&&(aux2.getTipo().equals("Boolean")||aux2.getTipo().equals("Cond"))){
					RESULT = new Nodo ((String)v, "Cond", (Nodo)e1, (Nodo)e2);
					System.out.println("Condicion or ambigua");
				} else System.err.println("Error semántico: Expresión de tipo inesperado en operación booleana" + " (Linea " + e1left + ")");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // condicion ::= condicion OR condicion 
            {
              Object RESULT =null;
		int c1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int c1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object c1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int c2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int c2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object c2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
				Nodo aux1 = (Nodo) c1;
				Nodo aux2 = (Nodo) c2;
				if((aux1.getTipo().equals("Boolean")||aux1.getTipo().equals("Cond"))&&(aux2.getTipo().equals("Boolean")||aux2.getTipo().equals("Cond"))){
					RESULT = new Nodo ((String)v, "Cond", (Nodo)c1, (Nodo)c2);
					System.out.println("Condicion or simple");
				} else System.err.println("Error semántico: Expresión de tipo inesperado en operación booleana" + " (Linea " + c1left + ")");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // condicion ::= NOT expresion 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
				Nodo aux = (Nodo) e;
				if(aux.getTipo().equals("Boolean") || aux.getTipo().equals("Cond")){
					RESULT = new Nodo ((String)v, "Cond", (Nodo) e, null);
					System.out.println("Condicion not ambigua");
				} else System.err.println("Error semántico: Expresión de tipo inesperado en operación booleana" + " (Linea " + vleft + ")");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // condicion ::= NOT condicion 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
				Nodo aux = (Nodo) e1;
				if(aux.getTipo().equals("Boolean") || aux.getTipo().equals("Cond")){
					RESULT = new Nodo ((String)v, "Cond", (Nodo) e1, null);
					System.out.println("Condicion not simple");
				} else System.err.println("Error semántico: Expresión de tipo inesperado en operación de comparación" + " (Linea " + e1left + ")");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // condicion ::= expresion MAYOR expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
				Nodo aux1 = (Nodo)e1;
				Nodo aux2 = (Nodo)e2;
				if((aux1.getTipo().equals("Integer")||aux1.getTipo().equals("OP"))&&(aux2.getTipo().equals("Integer")||aux2.getTipo().equals("OP"))){
					RESULT = new Nodo((String)v, "OP", (Nodo)e1, (Nodo)e2);
					System.out.println("Condicion mayor");
				} else System.err.println("Error semántico: Expresión de tipo inesperado en operación de comparación" + " (Linea " + e1left + ")");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // condicion ::= expresion MENOR expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
				Nodo aux1 = (Nodo)e1;
				Nodo aux2 = (Nodo)e2;
				if((aux1.getTipo().equals("Integer")||aux1.getTipo().equals("OP"))&&(aux2.getTipo().equals("Integer")||aux2.getTipo().equals("OP"))){
					RESULT = new Nodo((String)v, "OP", (Nodo)e1, (Nodo)e2);
					System.out.println("Condicion menor");
				} else System.err.println("Error semántico: Expresión de tipo inesperado en operación de comparación" + " (Linea " + e1left + ")");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // condicion ::= expresion MAYORIGUAL expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
				Nodo aux1 = (Nodo)e1;
				Nodo aux2 = (Nodo)e2;
				if((aux1.getTipo().equals("Integer")||aux1.getTipo().equals("OP"))&&(aux2.getTipo().equals("Integer")||aux2.getTipo().equals("OP"))){
					RESULT = new Nodo((String)v, "OP", (Nodo)e1, (Nodo)e2);
					System.out.println("Condicion mayorigual");
				} else System.err.println("Error semántico: Expresión de tipo inesperado en operación de comparación" + " (Linea " + e1left + ")");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // condicion ::= expresion IGUAL expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
				Nodo aux1 = (Nodo)e1;
				Nodo aux2 = (Nodo)e2;
				if((aux1.getTipo().equals("Integer")||aux1.getTipo().equals("OP"))&&(aux2.getTipo().equals("Integer")||aux2.getTipo().equals("OP"))){
					RESULT = new Nodo((String)v, "OP", (Nodo)e1, (Nodo)e2);
					System.out.println("Condicion igual");
				} else System.err.println("Error semántico: Expresión de tipo inesperado en operación de comparación" + " (Linea " + e1left + ")");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // condicion ::= expresion MENORIGUAL expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
				Nodo aux1 = (Nodo)e1;
				Nodo aux2 = (Nodo)e2;
				if((aux1.getTipo().equals("Integer")||aux1.getTipo().equals("OP"))&&(aux2.getTipo().equals("Integer")||aux2.getTipo().equals("OP"))){
					RESULT = new Nodo((String)v, "OP", (Nodo)e1, (Nodo)e2);
					System.out.println("Condicion menorigual");
				} else System.err.println("Error semántico: Expresión de tipo inesperado en operación de comparación" + " (Linea " + e1left + ")");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // condicion ::= expresion DISTINTOA expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
				Nodo aux1 = (Nodo)e1;
				Nodo aux2 = (Nodo)e2;
				if((aux1.getTipo().equals("Integer")||aux1.getTipo().equals("OP"))&&(aux2.getTipo().equals("Integer")||aux2.getTipo().equals("OP"))){
					RESULT = new Nodo((String)v, "OP", (Nodo)e1, (Nodo)e2);
					System.out.println("Condicion distintoa");
				} else System.err.println("Error semántico: Expresión de tipo inesperado en operación de comparación" + " (Linea " + e1left + ")");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // condicion ::= ABRIRPARENTESIS condicion CERRARPARENTESIS 
            {
              Object RESULT =null;
		int c1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int c1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object c1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
				RESULT = new Nodo("Parentesis", "Cond", (Nodo)c1, null);
				System.out.println("Condicion completa");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // condicion ::= FALSE 
            {
              Object RESULT =null;
		
				RESULT = new Nodo("False", "Boolean", null, null);
				System.out.println("Condicion false");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // condicion ::= TRUE 
            {
              Object RESULT =null;
		
				RESULT = new Nodo("True", "Boolean", null, null);
				System.out.println("Condicion true");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // sentencia ::= error PUNTOCOMA 
            {
              Object RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		System.err.println("Error sintáctico: sentencia mal escrita en linea " + pleft);
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // sentencia ::= WHILE expresion DO bloqueCodigo END WHILE PUNTOCOMA 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		
					System.out.println("Bucle con expresion");
					RESULT = new Nodo("While","Sent", (Nodo)e, (Nodo)b);
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // sentencia ::= WHILE condicion DO bloqueCodigo END WHILE PUNTOCOMA 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		
					System.out.println("Bucle");
					RESULT = new Nodo("While","Sent", (Nodo)c, (Nodo)b);
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // sentencia ::= IF expresion THEN bloqueCodigo ELSE bloqueCodigo END IF PUNTOCOMA 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-7)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-7)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-7)).value;
		int b1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).left;
		int b1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).right;
		Object b1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).value;
		int b2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int b2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		Object b2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		
					System.out.println("If con else con expresion");
					RESULT = new Nodo("IfElse", "Sent", (Nodo)e, (Nodo)b1, (Nodo)b2);
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-8)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // sentencia ::= IF expresion THEN bloqueCodigo END IF PUNTOCOMA 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		
					System.out.println("If simple con expresion");
					RESULT = new Nodo("If","Sent", (Nodo)e, (Nodo)b);
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // sentencia ::= IF condicion THEN bloqueCodigo ELSE bloqueCodigo END IF PUNTOCOMA 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-7)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-7)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-7)).value;
		int b1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).left;
		int b1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).right;
		Object b1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).value;
		int b2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int b2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		Object b2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		
					System.out.println("If con else");
					RESULT = new Nodo("IfElse", "Sent", (Nodo)c, (Nodo)b1, (Nodo)b2);
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-8)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // sentencia ::= IF condicion THEN bloqueCodigo END IF PUNTOCOMA 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		
					System.out.println("If simple");
					RESULT = new Nodo("If","Sent", (Nodo)c, (Nodo)b);
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // sentencia ::= SKIP 
            {
              Object RESULT =null;
		
					System.out.println("Skip");
					RESULT = new Nodo("Skip", "Sent", null, null); //Esta sentencia es especial y no hace nada
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // sentencia ::= WRITE condicion PUNTOCOMA 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
					System.out.println("Write de condicion");
					RESULT = new Nodo("Write", "Sent", (Nodo)c, null);
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // sentencia ::= WRITE expresion PUNTOCOMA 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
					System.out.println("Write de expresion");
					RESULT = new Nodo("Write", "Sent", (Nodo)e, null);
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // sentencia ::= READ expresion PUNTOCOMA 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
					System.out.println("Read");
					RESULT = new Nodo("Read", "Sent", (Nodo)e, null);
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // sentencia ::= IDENTIFICADOR ASIGNACION condicion PUNTOCOMA 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
						Nodo auxn = new Nodo((String)v, "Boolean", null, null);
						String aux = ParserCup.tablaSimbolos.getSimbolo(auxn.getValor());
						if (aux.equals("Void")){
							//No existe en la tabla. Error
							System.err.println("Error semántico: Asignación a variable no declarada (Linea " + vleft + ", Pos " + vright +")");
						}
						else{ //Si existe, comprobamos tipo
							if(!aux.equals("Boolean")){
								//Tipo incorrecto. Error
								System.err.println("Error semántico: Asignación booleana a variable tipo " + aux + " (Linea " + vleft + ", Pos " + vright +")");
							}
							else{
								System.out.println("Asignacion Booleana");
								RESULT = new Nodo("Asig", "Sent", auxn, (Nodo)c);
							}
						}
					
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // sentencia ::= IDENTIFICADOR ASIGNACION expresion PUNTOCOMA 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
					Nodo auxn = new Nodo((String)v, "Integer", null, null);
					String aux = ParserCup.tablaSimbolos.getSimbolo(auxn.getValor());
					if (aux.equals("Void")){
						//No existe en la tabla. Error
						System.err.println("Error semántico: Asignación a variable no declarada (Linea " + vleft + ", Pos " + vright +")");
					}
					else{ //Si existe, comprobamos tipo
						if(!aux.equals("Integer")){
							//Tipo incorrecto. Error
							System.err.println("Error semántico: Asignación aritmetica a variable tipo " + aux + " (Linea " + vleft + ", Pos " + vright +")");
						}
						else {
							System.out.println("Asignacion Aritmetica");
							RESULT = new Nodo("Asig", "Sent", auxn, (Nodo)e);
						}
					}
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // bloqueCodigo ::= sentencia 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
					System.out.println("Una sentencia de bloque");
					RESULT = new Nodo("Codigo", "",(Nodo)s, null); 
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("bloqueCodigo",5, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // bloqueCodigo ::= sentencia bloqueCodigo 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
					System.out.println("Bloque codigo");
					RESULT = new Nodo("Codigo", "", (Nodo)s, (Nodo)b);
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("bloqueCodigo",5, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // declaracion ::= IDENTIFICADOR 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
					System.out.println("Una variable");
					RESULT = new Nodo((String)v, "Var", null, null);
					ParserCup.colaDeclarados.add((String)v);
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("declaracion",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // declaracion ::= declaracion COMA IDENTIFICADOR 
            {
              Object RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
					System.out.println("Más de una variable");
					RESULT = new Nodo((String)v, "Var", (Nodo)d, null);
					ParserCup.colaDeclarados.add((String) v);
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("declaracion",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // declarar ::= error PUNTOCOMA 
            {
              Object RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 System.err.println("Error sintáctico: Declaración mal formada en linea " + pleft);
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("declarar",3, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // declarar ::= VAR declaracion DOSPUNTOS BOOLEAN PUNTOCOMA 
            {
              Object RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		System.out.println("Boolean declarado");
				while(!ParserCup.colaDeclarados.isEmpty()){
					if (ParserCup.tablaSimbolos.getSimbolo(ParserCup.colaDeclarados.peek()).equals("Undefined")){
						//No existe en la tabla. Se puede insertar
						String aux = (String)ParserCup.colaDeclarados.remove();
						ParserCup.tablaSimbolos.insertarSimbolo(aux,"Boolean");
						RESULT = new Nodo("Declarar", "Booleans", (Nodo)d, null);
					}
					else{
						System.err.println("Error semántico: Más de una variable de nombre " + ParserCup.colaDeclarados.remove() + " (Linea " + vleft + ")");
					}
				}
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("declarar",3, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // declarar ::= VAR declaracion DOSPUNTOS INTEGER PUNTOCOMA 
            {
              Object RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		System.out.println("Integer declarado");
				while(!ParserCup.colaDeclarados.isEmpty()){
					if (ParserCup.tablaSimbolos.getSimbolo(ParserCup.colaDeclarados.peek()).equals("Undefined")){
						//No existe en la tabla. Se puede insertar
						String aux = (String)ParserCup.colaDeclarados.remove();
						ParserCup.tablaSimbolos.insertarSimbolo(aux,"Integer");
						RESULT = new Nodo("Declarar", "Integers", (Nodo)d, null);
					}
					else{
						System.err.println("Error semántico: Más de una variable de nombre " + ParserCup.colaDeclarados.remove() + " (Linea " + vleft + ")");
					}
				}
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("declarar",3, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // bloqueDeclaraciones ::= declarar bloqueDeclaraciones 
            {
              Object RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
							System.out.println("Declaraciones acabadas");
							RESULT = new Nodo("Declaraciones","", (Nodo)d, (Nodo)b);
						
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("bloqueDeclaraciones",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // bloqueDeclaraciones ::= declarar 
            {
              Object RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
							System.out.println("Declaracion acabada");
							RESULT = new Nodo("Declaraciones", "", (Nodo)d, null);
						
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("bloqueDeclaraciones",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // declararProg ::= PROGRAM IDENTIFICADOR IS 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
				ParserCup.tablaSimbolos.insertarSimbolo((String)v,"pseudo");
				System.out.println("Comanzando programa llamado " + v);
				RESULT = new Nodo("DeclarPrograma", "", null, null);
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("declararProg",1, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= declararProg BEGIN bloqueCodigo END 
            {
              Object RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
				 System.out.println("Programa completo sin declaraciones");
			 ParserCup.arbol.setRoot(new Nodo("ProgramaSimple", "", (Nodo)d, (Nodo)b));
			 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= declararProg bloqueDeclaraciones BEGIN bloqueCodigo END 
            {
              Object RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).value;
		int bdleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int bdright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		Object bd = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int bcleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int bcright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object bc = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
				System.out.println("Programa completo");
				ParserCup.arbol.setRoot(new Nodo("Programa", "", (Nodo)d, (Nodo)bd, (Nodo)bc));
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		RESULT = start_val;
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserCup$parser.done_parsing();
          return CUP$ParserCup$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

