
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Dec 03 14:10:39 CET 2016
//----------------------------------------------------

package compilador;

import java_cup.runtime.*;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.File;
import java.util.Scanner;
import compilador.TablaSimbolos;
import java.util.Queue;
import java.util.LinkedList;
import java.util.NoSuchElementException;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sat Dec 03 14:10:39 CET 2016
  */
public class ParserCup extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ParserCup() {super();}

  /** Constructor which sets the default scanner. */
  public ParserCup(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserCup(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\054\000\002\002\004\000\002\002\007\000\002\002" +
    "\006\000\002\003\005\000\002\004\003\000\002\004\004" +
    "\000\002\005\007\000\002\005\007\000\002\006\005\000" +
    "\002\006\003\000\002\007\004\000\002\007\003\000\002" +
    "\011\006\000\002\011\006\000\002\011\005\000\002\011" +
    "\005\000\002\011\005\000\002\011\003\000\002\011\011" +
    "\000\002\011\013\000\002\011\011\000\002\011\013\000" +
    "\002\011\011\000\002\011\011\000\002\010\003\000\002" +
    "\010\003\000\002\010\005\000\002\010\005\000\002\010" +
    "\005\000\002\010\005\000\002\010\005\000\002\010\005" +
    "\000\002\010\005\000\002\010\004\000\002\010\004\000" +
    "\002\010\005\000\002\010\005\000\002\012\003\000\002" +
    "\012\003\000\002\012\005\000\002\012\005\000\002\012" +
    "\005\000\002\012\005\000\002\012\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\166\000\004\004\006\001\002\000\004\002\170\001" +
    "\002\000\006\006\012\010\011\001\002\000\004\051\007" +
    "\001\002\000\004\005\010\001\002\000\006\006\ufffe\010" +
    "\ufffe\001\002\000\004\051\157\001\002\000\016\013\021" +
    "\014\023\015\017\016\025\020\026\051\022\001\002\000" +
    "\004\006\016\001\002\000\006\006\ufffd\010\011\001\002" +
    "\000\004\006\ufffc\001\002\000\016\013\021\014\023\015" +
    "\017\016\025\020\026\051\022\001\002\000\022\007\ufff0" +
    "\013\ufff0\014\ufff0\015\ufff0\016\ufff0\020\ufff0\022\ufff0\051" +
    "\ufff0\001\002\000\004\007\154\001\002\000\010\044\052" +
    "\050\035\051\030\001\002\000\004\030\145\001\002\000" +
    "\016\025\027\026\031\027\034\044\032\050\035\051\030" +
    "\001\002\000\022\007\ufff6\013\021\014\023\015\017\016" +
    "\025\020\026\022\ufff6\051\022\001\002\000\016\025\027" +
    "\026\031\027\034\044\032\050\035\051\030\001\002\000" +
    "\016\025\027\026\031\027\034\044\032\050\035\051\030" +
    "\001\002\000\016\025\027\026\031\027\034\044\032\050" +
    "\035\051\030\001\002\000\042\017\uffdc\021\uffdc\023\uffdc" +
    "\024\uffdc\031\uffdc\032\uffdc\033\uffdc\034\uffdc\035\uffdc\036" +
    "\uffdc\037\uffdc\040\uffdc\041\uffdc\042\uffdc\043\uffdc\045\uffdc" +
    "\001\002\000\016\017\uffe9\021\uffe9\023\uffe9\024\uffe9\043" +
    "\uffe9\045\uffe9\001\002\000\016\025\027\026\031\027\034" +
    "\044\032\050\035\051\030\001\002\000\010\021\101\023" +
    "\100\024\102\001\002\000\016\017\uffe8\021\uffe8\023\uffe8" +
    "\024\uffe8\043\uffe8\045\uffe8\001\002\000\042\017\uffdb\021" +
    "\uffdb\023\uffdb\024\uffdb\031\uffdb\032\uffdb\033\uffdb\034\uffdb" +
    "\035\uffdb\036\uffdb\037\uffdb\040\uffdb\041\uffdb\042\uffdb\043" +
    "\uffdb\045\uffdb\001\002\000\030\021\043\031\037\032\040" +
    "\033\047\034\046\035\045\036\042\037\041\040\051\041" +
    "\044\042\050\001\002\000\010\044\052\050\035\051\030" +
    "\001\002\000\010\044\052\050\035\051\030\001\002\000" +
    "\010\044\052\050\035\051\030\001\002\000\010\044\052" +
    "\050\035\051\030\001\002\000\016\013\021\014\023\015" +
    "\017\016\025\020\026\051\022\001\002\000\010\044\052" +
    "\050\035\051\030\001\002\000\010\044\052\050\035\051" +
    "\030\001\002\000\010\044\052\050\035\051\030\001\002" +
    "\000\010\044\052\050\035\051\030\001\002\000\010\044" +
    "\052\050\035\051\030\001\002\000\010\044\052\050\035" +
    "\051\030\001\002\000\010\044\052\050\035\051\030\001" +
    "\002\000\042\017\uffd8\021\uffd8\023\uffd8\024\uffd8\031\uffd8" +
    "\032\uffd8\033\uffd8\034\uffd8\035\uffd8\036\uffd8\037\uffd8\040" +
    "\uffd8\041\044\042\050\043\uffd8\045\uffd8\001\002\000\014" +
    "\037\041\040\051\041\044\042\050\045\055\001\002\000" +
    "\042\017\uffda\021\uffda\023\uffda\024\uffda\031\uffda\032\uffda" +
    "\033\uffda\034\uffda\035\uffda\036\uffda\037\uffda\040\uffda\041" +
    "\uffda\042\uffda\043\uffda\045\uffda\001\002\000\042\017\uffd6" +
    "\021\uffd6\023\uffd6\024\uffd6\031\uffd6\032\uffd6\033\uffd6\034" +
    "\uffd6\035\uffd6\036\uffd6\037\uffd6\040\uffd6\041\uffd6\042\uffd6" +
    "\043\uffd6\045\uffd6\001\002\000\026\017\uffe4\021\uffe4\023" +
    "\uffe4\024\uffe4\037\041\040\051\041\044\042\050\043\uffe4" +
    "\045\uffe4\001\002\000\026\017\uffe1\021\uffe1\023\uffe1\024" +
    "\uffe1\037\041\040\051\041\044\042\050\043\uffe1\045\uffe1" +
    "\001\002\000\026\017\uffe3\021\uffe3\023\uffe3\024\uffe3\037" +
    "\041\040\051\041\044\042\050\043\uffe3\045\uffe3\001\002" +
    "\000\042\017\uffd7\021\uffd7\023\uffd7\024\uffd7\031\uffd7\032" +
    "\uffd7\033\uffd7\034\uffd7\035\uffd7\036\uffd7\037\uffd7\040\uffd7" +
    "\041\uffd7\042\uffd7\043\uffd7\045\uffd7\001\002\000\006\007" +
    "\065\022\064\001\002\000\016\013\021\014\023\015\017" +
    "\016\025\020\026\051\022\001\002\000\004\020\066\001" +
    "\002\000\004\043\067\001\002\000\022\007\uffed\013\uffed" +
    "\014\uffed\015\uffed\016\uffed\020\uffed\022\uffed\051\uffed\001" +
    "\002\000\004\007\071\001\002\000\004\020\072\001\002" +
    "\000\004\043\073\001\002\000\022\007\uffec\013\uffec\014" +
    "\uffec\015\uffec\016\uffec\020\uffec\022\uffec\051\uffec\001\002" +
    "\000\026\017\uffe6\021\uffe6\023\uffe6\024\uffe6\037\041\040" +
    "\051\041\044\042\050\043\uffe6\045\uffe6\001\002\000\042" +
    "\017\uffd9\021\uffd9\023\uffd9\024\uffd9\031\uffd9\032\uffd9\033" +
    "\uffd9\034\uffd9\035\uffd9\036\uffd9\037\uffd9\040\uffd9\041\044" +
    "\042\050\043\uffd9\045\uffd9\001\002\000\026\017\uffe2\021" +
    "\uffe2\023\uffe2\024\uffe2\037\041\040\051\041\044\042\050" +
    "\043\uffe2\045\uffe2\001\002\000\026\017\uffe5\021\uffe5\023" +
    "\uffe5\024\uffe5\037\041\040\051\041\044\042\050\043\uffe5" +
    "\045\uffe5\001\002\000\016\025\027\026\031\027\034\044" +
    "\032\050\035\051\030\001\002\000\016\013\021\014\023" +
    "\015\017\016\025\020\026\051\022\001\002\000\016\025" +
    "\027\026\031\027\034\044\032\050\035\051\030\001\002" +
    "\000\016\017\uffde\021\uffde\023\uffde\024\uffde\043\uffde\045" +
    "\uffde\001\002\000\026\031\037\032\040\033\047\034\046" +
    "\035\045\036\042\037\041\040\051\041\044\042\050\001" +
    "\002\000\006\007\107\022\106\001\002\000\016\013\021" +
    "\014\023\015\017\016\025\020\026\051\022\001\002\000" +
    "\004\020\110\001\002\000\004\043\111\001\002\000\022" +
    "\007\uffef\013\uffef\014\uffef\015\uffef\016\uffef\020\uffef\022" +
    "\uffef\051\uffef\001\002\000\004\007\113\001\002\000\004" +
    "\020\114\001\002\000\004\043\115\001\002\000\022\007" +
    "\uffee\013\uffee\014\uffee\015\uffee\016\uffee\020\uffee\022\uffee" +
    "\051\uffee\001\002\000\016\017\uffdd\021\uffdd\023\uffdd\024" +
    "\uffdd\043\uffdd\045\uffdd\001\002\000\010\023\100\024\102" +
    "\045\121\001\002\000\030\031\037\032\040\033\047\034" +
    "\046\035\045\036\042\037\041\040\051\041\044\042\050" +
    "\045\055\001\002\000\016\017\uffe7\021\uffe7\023\uffe7\024" +
    "\uffe7\043\uffe7\045\uffe7\001\002\000\016\017\uffe0\021\uffe0" +
    "\023\uffe0\024\uffe0\043\uffe0\045\uffe0\001\002\000\042\017" +
    "\uffdf\021\uffdf\023\uffdf\024\uffdf\031\037\032\040\033\047" +
    "\034\046\035\045\036\042\037\041\040\051\041\044\042" +
    "\050\043\uffdf\045\uffdf\001\002\000\010\017\133\023\100" +
    "\024\102\001\002\000\030\017\126\031\037\032\040\033" +
    "\047\034\046\035\045\036\042\037\041\040\051\041\044" +
    "\042\050\001\002\000\016\013\021\014\023\015\017\016" +
    "\025\020\026\051\022\001\002\000\004\007\130\001\002" +
    "\000\004\016\131\001\002\000\004\043\132\001\002\000" +
    "\022\007\uffea\013\uffea\014\uffea\015\uffea\016\uffea\020\uffea" +
    "\022\uffea\051\uffea\001\002\000\016\013\021\014\023\015" +
    "\017\016\025\020\026\051\022\001\002\000\004\007\135" +
    "\001\002\000\004\016\136\001\002\000\004\043\137\001" +
    "\002\000\022\007\uffeb\013\uffeb\014\uffeb\015\uffeb\016\uffeb" +
    "\020\uffeb\022\uffeb\051\uffeb\001\002\000\006\007\ufff7\022" +
    "\ufff7\001\002\000\010\023\100\024\102\043\144\001\002" +
    "\000\030\031\037\032\040\033\047\034\046\035\045\036" +
    "\042\037\041\040\051\041\044\042\050\043\143\001\002" +
    "\000\022\007\ufff2\013\ufff2\014\ufff2\015\ufff2\016\ufff2\020" +
    "\ufff2\022\ufff2\051\ufff2\001\002\000\022\007\ufff1\013\ufff1" +
    "\014\ufff1\015\ufff1\016\ufff1\020\ufff1\022\ufff1\051\ufff1\001" +
    "\002\000\016\025\027\026\031\027\034\044\032\050\035" +
    "\051\030\001\002\000\010\023\100\024\102\043\151\001" +
    "\002\000\030\031\037\032\040\033\047\034\046\035\045" +
    "\036\042\037\041\040\051\041\044\042\050\043\150\001" +
    "\002\000\022\007\ufff5\013\ufff5\014\ufff5\015\ufff5\016\ufff5" +
    "\020\ufff5\022\ufff5\051\ufff5\001\002\000\022\007\ufff4\013" +
    "\ufff4\014\ufff4\015\ufff4\016\ufff4\020\ufff4\022\ufff4\051\ufff4" +
    "\001\002\000\014\037\041\040\051\041\044\042\050\043" +
    "\153\001\002\000\022\007\ufff3\013\ufff3\014\ufff3\015\ufff3" +
    "\016\ufff3\020\ufff3\022\ufff3\051\ufff3\001\002\000\004\002" +
    "\000\001\002\000\004\007\156\001\002\000\004\002\uffff" +
    "\001\002\000\006\046\ufff8\047\ufff8\001\002\000\006\046" +
    "\161\047\162\001\002\000\004\051\167\001\002\000\006" +
    "\011\163\012\164\001\002\000\004\043\166\001\002\000" +
    "\004\043\165\001\002\000\006\006\ufffa\010\ufffa\001\002" +
    "\000\006\006\ufffb\010\ufffb\001\002\000\006\046\ufff9\047" +
    "\ufff9\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\166\000\006\002\003\003\004\001\001\000\002\001" +
    "\001\000\006\004\012\005\013\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\006\157\001" +
    "\001\000\006\007\154\011\023\001\001\000\002\001\001" +
    "\000\006\004\014\005\013\001\001\000\002\001\001\000" +
    "\006\007\017\011\023\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\012\151\001\001\000\002\001\001\000" +
    "\006\010\140\012\141\001\001\000\006\007\137\011\023" +
    "\001\001\000\006\010\123\012\124\001\001\000\006\010" +
    "\032\012\035\001\001\000\006\010\121\012\122\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\010\116\012" +
    "\117\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\012\076\001\001\000" +
    "\004\012\075\001\001\000\004\012\074\001\001\000\004" +
    "\012\073\001\001\000\006\007\062\011\023\001\001\000" +
    "\004\012\061\001\001\000\004\012\060\001\001\000\004" +
    "\012\057\001\001\000\004\012\056\001\001\000\004\012" +
    "\055\001\001\000\004\012\052\001\001\000\004\012\053" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\007\067\011\023\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\010\115\012\103\001\001\000\006\007\104\011\023" +
    "\001\001\000\006\010\102\012\103\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\007\111" +
    "\011\023\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\007\126\011\023\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\007" +
    "\133\011\023\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\010\145\012\146\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserCup$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserCup$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserCup$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




static public TablaSimbolos tablaSimbolos;
static public Queue<String> colaDeclarados; //Utilizado para procesar declaraciones multiples en una linea

/** MAIN - LEER TOKENS */

public static void main (String argv[]) throws Exception
  {
    /*Comprobacacion del nombre del archivo*/
    if(argv.length<1){
    	System.err.println("Uso: java Parser nombreArchivo");
    	System.exit(1);
    }
    /* Asegurarse que la extension del archivo es correcta*/
	int aux = argv[0].indexOf('.');
	if(aux==-1){
		System.err.println("Error: El archivo debe acabar en .prog");
		System.exit(1);
	} else{
		if(!argv[0].substring(aux+1).equals("prog")){
			System.err.println("Error: El archivo debe acabar en .prog");
			System.exit(1);
		}
	}
	/* Inicializaion*/
	File archivo = new File(argv[0]);
    FileReader fr = new FileReader(archivo);
    tablaSimbolos = new TablaSimbolos();
    colaDeclarados = new LinkedList();
    Scan lex = new Scan(fr);
    ParserCup p = new ParserCup(lex);
    p.parse();
}

/** NOTIFICAR ERROR DE SINTAXIS */
public void syntax_error(Symbol s) {
  report_error("Error de sintaxis linea " + s.left, null);
}

/** NOTIFICAR ERROR FATAL Y SALIR */
public void report_fatal_error(String message, Object info) {
  done_parsing();
  report_error("Error de sintaxis fatal : "
  + "No se puede recuperar del error y continuar con el analisis - "
  + message + " ",(Symbol)info);
  report_error("** Final del analisis.", null);
  System.exit(1);
}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ParserCup$actions {
  private final ParserCup parser;

  /** Constructor */
  CUP$ParserCup$actions(ParserCup parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$ParserCup$do_action(
    int                        CUP$ParserCup$act_num,
    java_cup.runtime.lr_parser CUP$ParserCup$parser,
    java.util.Stack            CUP$ParserCup$stack,
    int                        CUP$ParserCup$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserCup$result;

      /* select the action based on the action number */
      switch (CUP$ParserCup$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expresion ::= expresion DIVISION expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
					if(e1.equals("Integer")&&e2.equals("Integer")){
						RESULT = new String();
						System.out.println("Expresion división");
					} else System.err.println("Error semántico: Expresión de tipo inesperado en operación de enteros" + " (Linea " + vleft + ")");
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expresion",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expresion ::= expresion MULTIPLICACION expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
					if(e1.equals("Integer")&&e2.equals("Integer")){
						RESULT = new String();
						System.out.println("Expresion multiplicacion");
					} else System.err.println("Error semántico: Expresión de tipo inesperado en operación de enteros" + " (Linea " + vleft + ")");
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expresion",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expresion ::= expresion RESTA expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
					if(e1.equals("Integer")&&e2.equals("Integer")){
						RESULT = new String();
						System.out.println("Expresion resto");
					} else System.err.println("Error semántico: Expresión de tipo inesperado en operación de enteros" + " (Linea " + vleft + ")");
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expresion",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expresion ::= expresion SUMA expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
					if(e1.equals("Integer")&&e2.equals("Integer")){
						RESULT = new String();
						System.out.println("Expresion suma");
					} else System.err.println("Error semántico: Expresión de tipo inesperado en operación de enteros" + " (Linea " + vleft + ")");
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expresion",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expresion ::= ABRIRPARENTESIS expresion CERRARPARENTESIS 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
					RESULT = new String(e1);
					System.out.println("expresion anidada");
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expresion",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expresion ::= ENTERO 
            {
              Object RESULT =null;
		
					RESULT = new String("Integer");
					System.out.println("Expresion Entero");
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expresion",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expresion ::= IDENTIFICADOR 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
					String aux = ParserCup.tablaSimbolos.getSimbolo((String)v);
					if (aux.equals("Void")){
						//No existe en la tabla. Error
						System.err.println("Error semántico: Llamada a variable no declarada" + " (Linea " + vleft + ", Pos " + vright +")");
					} else {
						RESULT = new String(aux);
					}
					System.out.println("Expresion Identificador tipo " + aux);
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expresion",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // condicion ::= condicion AND condicion 
            {
              Object RESULT =null;
		System.out.println("Condicion and");
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // condicion ::= condicion OR condicion 
            {
              Object RESULT =null;
		System.out.println("Condicion or");
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // condicion ::= NOT expresion 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
				if(e.equals("Boolean")){
					RESULT = new String("Boolean");
					System.out.println("Condicion not ambigua");
				} else System.err.println("Error semántico: Expresión de tipo inesperado en operación booleana" + " (Linea " + vleft + ")");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // condicion ::= NOT condicion 
            {
              Object RESULT =null;
		System.out.println("Condicion not bool");
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // condicion ::= expresion MAYOR expresion 
            {
              Object RESULT =null;
		System.out.println("Condicion mayor");
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // condicion ::= expresion MENOR expresion 
            {
              Object RESULT =null;
		System.out.println("Condicion menor");
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // condicion ::= expresion MAYORIGUAL expresion 
            {
              Object RESULT =null;
		System.out.println("Condicion mayorigual");
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // condicion ::= expresion IGUAL expresion 
            {
              Object RESULT =null;
		System.out.println("Condicion igual");
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // condicion ::= expresion MENORIGUAL expresion 
            {
              Object RESULT =null;
		System.out.println("Condicion menorigual");
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // condicion ::= expresion DISTINTOA expresion 
            {
              Object RESULT =null;
		System.out.println("Condicion distintoa");
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // condicion ::= ABRIRPARENTESIS condicion CERRARPARENTESIS 
            {
              Object RESULT =null;
		int c1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int c1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object c1 = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
				RESULT = new String(c1);
				System.out.println("Condicion completa");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // condicion ::= FALSE 
            {
              Object RESULT =null;
		
				RESULT = new String("Boolean");
				System.out.println("Condicion false");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // condicion ::= TRUE 
            {
              Object RESULT =null;
		
				RESULT = new String("Boolean");
				System.out.println("Condicion true");
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condicion",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // sentencia ::= WHILE expresion DO bloqueCodigo END WHILE PUNTOCOMA 
            {
              Object RESULT =null;
		System.out.println("Bucle con expresion!");
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // sentencia ::= WHILE condicion DO bloqueCodigo END WHILE PUNTOCOMA 
            {
              Object RESULT =null;
		System.out.println("Bucle");
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // sentencia ::= IF expresion THEN bloqueCodigo ELSE bloqueCodigo END IF PUNTOCOMA 
            {
              Object RESULT =null;
		System.out.println("If con else con expresion!");
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-8)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // sentencia ::= IF expresion THEN bloqueCodigo END IF PUNTOCOMA 
            {
              Object RESULT =null;
		System.out.println("If simple con expresion!");
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // sentencia ::= IF condicion THEN bloqueCodigo ELSE bloqueCodigo END IF PUNTOCOMA 
            {
              Object RESULT =null;
		System.out.println("If con else");
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-8)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // sentencia ::= IF condicion THEN bloqueCodigo END IF PUNTOCOMA 
            {
              Object RESULT =null;
		System.out.println("If simple");
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // sentencia ::= SKIP 
            {
              Object RESULT =null;
		System.out.println("Skip");
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // sentencia ::= WRITE condicion PUNTOCOMA 
            {
              Object RESULT =null;
		
					System.out.println("Write de condicion");
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // sentencia ::= WRITE expresion PUNTOCOMA 
            {
              Object RESULT =null;
		
					System.out.println("Write de expresion");
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // sentencia ::= READ expresion PUNTOCOMA 
            {
              Object RESULT =null;
		
					System.out.println("Read");
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // sentencia ::= IDENTIFICADOR ASIGNACION condicion PUNTOCOMA 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		String aux = ParserCup.tablaSimbolos.getSimbolo((String)v);
						if (aux.equals("Void")){
							//No existe en la tabla. Error
							System.err.println("Error semántico: Asignación a variable no declarada (Linea " + vleft + ", Pos " + vright +")");
						}
						else{ //Si existe, comprobamos tipo
							if(!aux.equals("Boolean")){
								//Tipo incorrecto. Error
								System.err.println("Error semántico: Asignación booleana a variable tipo " + aux + " (Linea " + vleft + ", Pos " + vright +")");
							}
							else System.out.println("Asignacion Booleana");
						}
					
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // sentencia ::= IDENTIFICADOR ASIGNACION expresion PUNTOCOMA 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		String aux = ParserCup.tablaSimbolos.getSimbolo((String)v);
					if (aux.equals("Void")){
						//No existe en la tabla. Error
						System.err.println("Error semántico: Asignación a variable no declarada (Linea " + vleft + ", Pos " + vright +")");
					}
					else{ //Si existe, comprobamos tipo
						if(!aux.equals("Integer")){
							//Tipo incorrecto. Error
							System.err.println("Error semántico: Asignación aritmetica a variable tipo " + aux + " (Linea " + vleft + ", Pos " + vright +")");
						}
						else System.out.println("Asignacion Aritmetica");
					}
				
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // bloqueCodigo ::= sentencia 
            {
              Object RESULT =null;
		System.out.println("Una sentencia de bloque");
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("bloqueCodigo",5, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // bloqueCodigo ::= sentencia bloqueCodigo 
            {
              Object RESULT =null;
		System.out.println("Bloque codigo");
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("bloqueCodigo",5, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // declaracion ::= IDENTIFICADOR 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		System.out.println("Una variable");
									ParserCup.colaDeclarados.add((String)v);
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("declaracion",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // declaracion ::= declaracion COMA IDENTIFICADOR 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		System.out.println("Más de una variable");
													ParserCup.colaDeclarados.add((String)v);
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("declaracion",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // declarar ::= VAR declaracion DOSPUNTOS BOOLEAN PUNTOCOMA 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		System.out.println("Boolean declarado");
				while(!ParserCup.colaDeclarados.isEmpty()){
					if (ParserCup.tablaSimbolos.getSimbolo(ParserCup.colaDeclarados.peek()).equals("Void")){
						//No existe en la tabla. Se puede insertar
						String aux = (String)ParserCup.colaDeclarados.remove();
						ParserCup.tablaSimbolos.insertarSimbolo(aux,"Boolean");
					}
					else{
						System.err.println("Error semántico: Más de una variable de nombre " + ParserCup.colaDeclarados.remove() + " (Linea " + vleft + ")");
					}
				}
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("declarar",3, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // declarar ::= VAR declaracion DOSPUNTOS INTEGER PUNTOCOMA 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		System.out.println("Integer declarado");
				while(!ParserCup.colaDeclarados.isEmpty()){
					if (ParserCup.tablaSimbolos.getSimbolo(ParserCup.colaDeclarados.peek()).equals("Void")){
						//No existe en la tabla. Se puede insertar
						String aux = (String)ParserCup.colaDeclarados.remove();
						ParserCup.tablaSimbolos.insertarSimbolo(aux,"Integer");
					}
					else{
						System.err.println("Error semántico: Más de una variable de nombre " + ParserCup.colaDeclarados.remove() + " (Linea " + vleft + ")");
					}
				}
			
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("declarar",3, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // bloqueDeclaraciones ::= declarar bloqueDeclaraciones 
            {
              Object RESULT =null;
		System.out.println("Declaraciones acabadas");
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("bloqueDeclaraciones",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // bloqueDeclaraciones ::= declarar 
            {
              Object RESULT =null;
		System.out.println("Declaracion acabada");
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("bloqueDeclaraciones",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // declararProg ::= PROGRAM IDENTIFICADOR IS 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		ParserCup.tablaSimbolos.insertarSimbolo((String)v,"pseudo");
												System.out.println("Comanzando programa llamado " + v);
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("declararProg",1, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= declararProg BEGIN bloqueCodigo END 
            {
              Object RESULT =null;
		System.out.println("Programa completo sin declaraciones");
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= declararProg bloqueDeclaraciones BEGIN bloqueCodigo END 
            {
              Object RESULT =null;
		System.out.println("Programa completo");
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		RESULT = start_val;
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserCup$parser.done_parsing();
          return CUP$ParserCup$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

