
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Dec 03 13:18:51 CET 2016
//----------------------------------------------------

package compilador;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int DOSPUNTOS = 37;
  public static final int DISTINTOA = 28;
  public static final int ENTERO = 38;
  public static final int RESTA = 30;
  public static final int INTEGER = 7;
  public static final int PUNTOCOMA = 33;
  public static final int WRITE = 10;
  public static final int IDENTIFICADOR = 39;
  public static final int NOT = 19;
  public static final int MENORIGUAL = 23;
  public static final int IS = 3;
  public static final int AND = 17;
  public static final int IGUAL = 25;
  public static final int OR = 18;
  public static final int BEGIN = 4;
  public static final int SUMA = 29;
  public static final int IF = 14;
  public static final int MAYORIGUAL = 27;
  public static final int EOF = 0;
  public static final int BOOLEAN = 8;
  public static final int TRUE = 20;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int COMA = 36;
  public static final int MENOR = 24;
  public static final int ASIGNACION = 22;
  public static final int MAYOR = 26;
  public static final int ABRIRPARENTESIS = 34;
  public static final int ELSE = 16;
  public static final int SKIP = 11;
  public static final int READ = 9;
  public static final int WHILE = 12;
  public static final int THEN = 15;
  public static final int END = 5;
  public static final int CERRARPARENTESIS = 35;
  public static final int FALSE = 21;
  public static final int DIVISION = 32;
  public static final int VAR = 6;
  public static final int DO = 13;
  public static final int MULTIPLICACION = 31;
}

